---
- include: Debian.yml
  when: ansible_os_family == "Debian"

- include: RedHat.yml
  when: ansible_os_family == "RedHat"

- name: generate config file and restart shadowsocks-libev service
  template: src=config.json.j2 dest=/etc/shadowsocks-libev/config.json mode=0640

- name: enable tcp_fastopen for ipv4 if available
  sysctl: name="net.ipv4.tcp_fastopen" value="3" state=present reload=yes
  when: ss_fast_open == "true" and ansible_kernel | version_compare('3.7', '>=')

- name: set tcp_congestion_control for ipv4
  sysctl: name="net.ipv4.tcp_congestion_control" value={{ tcp_congestion_control }} state=present reload=yes
  when: tcp_congestion_control is defined

- name: enable and start shadowsocks-libev service
  service: name=shadowsocks-libev state=restarted enabled=yes
